import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/header'

import { UserProvider } from '@/contexts/user-context'
import { LocationProvider } from '@/contexts/location-context'
import { getCitiesAPI } from '@/api/location/location.api'
import Footer from '@/components/footer'
import { CartProvider } from '@/contexts/cart-context'
import React, { ReactNode } from 'react'
import { ToastContainer } from 'react-toastify'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    // Server-side'da şehirleri yükle
    let cities = [] as Awaited<ReturnType<typeof getCitiesAPI>>
    try {
        cities = await getCitiesAPI()
    } catch (error) {
        console.error('Şehirler yüklenirken hata oluştu:', error)
        cities = []
    }

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <UserProvider currentUser={null}>
                    <CartProvider isLoggedIn={false}>
                        <LocationProvider initialCities={cities}>
                            <Header cartItemCount={0} />
                            <ToastContainer
                                position="bottom-right"
                                autoClose={1000}
                            />
                            {children}
                            <Footer />
                        </LocationProvider>
                    </CartProvider>
                </UserProvider>
            </body>
        </html>
    )
}
