import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/header'

import { UserProvider } from '@/contexts/user-context'
import { LocationProvider } from '@/contexts/location-context'
import { getCitiesAPI } from '@/api/location/location.api'
import Footer from '@/components/footer'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // Server-side'da şehirleri yükle
    let cities = []
    try {
        cities = await getCitiesAPI()
    } catch (error) {
        console.error('Şehirler yüklenirken hata oluştu:', error)
        cities = []
    }

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <UserProvider currentUser={null}>
                    <LocationProvider initialCities={cities}>
                        <Header cartItemCount={0} />
                        {children}
                        <Footer />
                    </LocationProvider>
                </UserProvider>
            </body>
        </html>
    )
}
