import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/header'

import { UserProvider } from '@/contexts/user-context'
import Footer from '@/components/footer'
import { CartProvider } from '@/contexts/cart-context'
import React, { ReactNode } from 'react'
import { ToastContainer } from 'react-toastify'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <UserProvider currentUser={null}>
                    <CartProvider>
                        <Header />
                        <ToastContainer
                            position="bottom-right"
                            autoClose={1000}
                        />
                        {children}
                        <Footer />
                    </CartProvider>
                </UserProvider>
            </body>
        </html>
    )
}
